# Generated by Django 4.2.2 on 2023-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprediction',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
